name: Testing
on:
  - push
  - pull_request
 
jobs:
  macos-testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RGBDS
        run: |
          brew install rgbds
      - name: Run rgbasm on hardware.inc
        run: |
          rgbasm hardware.inc
  
  windows-testing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RGBDS
        run: |
          # Find the URL of the latest Win64 release with the GitHub API
          $githubLatestReleasesAPI = "https://api.github.com/repos/gbdev/rgbds/releases/latest"
          $githubReleaseURLs = ((Invoke-WebRequest $githubLatestReleasesAPI) | ConvertFrom-Json).assets.browser_download_url
          $githubWinReleaseURL = ($githubReleaseURLs | Select-String "win64").ToString()
          # Download latest release
          Invoke-WebRequest $githubWinReleaseURL -OutFile rgbds.zip
          Expand-Archive rgbds.zip
      - name: Run rgbasm on hardware.inc
        run: |
          rgbds/rgbasm.exe hardware.inc